### ISSUE TITLE
Android 11以上系统需要启用前台服务通知才能申请截图权限

### ISSUE THREAD

**Issue by segfault-bilibili** [icegreentee/magireco_autoBattle#126]
奇怪的报错

toast貌似没弹出来，需要弹出来

https://github.com/icegreentee/magireco_autoBattle/blob/5b464b6ae473e0a27f66454799bfd056d1107785/floatUI.js#L5227

**Comment by segfault-bilibili** [comment]
Fixed in https://github.com/icegreentee/magireco_autoBattle/pull/154/commits/593169c6ebf9ecbbc10c112f5eaac228395cca47

**Comment by segfault-bilibili** [comment]
```
2021-07-24 04:47:08.452/ERROR: Thread[main,5]:
java.lang.ClassCastException: org.mozilla.javascript.NativeJavaObject cannot be cast to org.mozilla.javascript.ScriptableObject
        at org.mozilla.javascript.NativeError.js_captureStackTrace(Unknown Source:8)
        at org.mozilla.javascript.NativeError.execIdCall(Unknown Source:54)
        at org.mozilla.javascript.IdFunctionObject.call(Unknown Source:7)
        at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:5497)
        at org.mozilla.javascript.Interpreter.interpret(Unknown Source:69)
        at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
        at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source:0)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source:33)
        at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:15)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(Unknown Source:90)
        at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(Unknown Source:11)
        at l.c.b.b.run(:1)
        at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(Unknown Source:44)
        at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(Unknown Source:12)
        at l.c.b.a.invoke(:2)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy7.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at com.stardust.autojs.core.looper.TimerThread.run(Unknown Source:72)
```

**Comment by segfault-bilibili** [comment]
Fixed in https://github.com/icegreentee/magireco_autoBattle/pull/154/commits/c0b230cfcc84160200f7c05467f7aabd7e61b8d7
